name: Android CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # important for full Git history and tags

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build and run tests
        run: ./gradlew clean assembleDebug testDebugUnitTest connectedDebugAndroidTest --stacktrace

      - name: Upload APK artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: UgandaEMR-Mobile-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
